/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.employeemanager;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jooan
 */
public class UpdateEmployee extends javax.swing.JDialog {
//Create object db and create new construct with this object as parameter
    BBDDManager db = new BBDDManager();

    Employee updatingEmployee;

    public UpdateEmployee(java.awt.Frame parent, boolean modal, BBDDManager db) {
        super(parent, modal);
        initComponents();
        this.db = db;
        setUpdateInvisible();

    }

    public UpdateEmployee(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtID = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtName = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxtAge = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTxtDepartment = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTxtSalary = new javax.swing.JTextPane();
        jBtnExit = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();
        jBtnLoad = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("UPDATE EMPLOYEE FORM");

        jScrollPane1.setViewportView(jTxtID);

        jScrollPane2.setViewportView(jTxtName);

        jScrollPane3.setViewportView(jTxtAge);

        jScrollPane4.setViewportView(jTxtDepartment);

        jScrollPane5.setViewportView(jTxtSalary);

        jBtnExit.setText("EXIT");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });

        jBtnUpdate.setText("UPDATE");
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        jBtnLoad.setText("LOAD");
        jBtnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoadActionPerformed(evt);
            }
        });

        jBtnCancel.setText("CANCEL");
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel3.setText("NAME");

        jLabel4.setText("AGE");

        jLabel5.setText("DEPARTMENT");

        jLabel6.setText("SALARY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jBtnExit)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnLoad)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnCancel)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnExit)
                    .addComponent(jBtnUpdate)
                    .addComponent(jBtnLoad)
                    .addComponent(jBtnCancel))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jBtnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoadActionPerformed
//Get id from input and validate
        boolean valid = true;

        int id = 0;

        try {

            id = Integer.parseInt(jTxtID.getText());

        } catch (Exception e) {
            valid = false;
            JOptionPane.showMessageDialog(this, "ID input invalid, please change it.");
        }
//if valid try find employee if found set all info into each textpane and show update and cancel buttons, load invisible.
        if (valid) {
            try {
                if (db.findEmployee(id) == true) {
                    try {
                        JOptionPane.showMessageDialog(this, "Employee found.");

                        updatingEmployee = db.getEmployee(id);

                        setUpdateVisible();

                        jTxtName.setText(updatingEmployee.getName());
                        jTxtAge.setText("" + updatingEmployee.getAge());
                        jTxtDepartment.setText(updatingEmployee.getDepartment());
                        jTxtSalary.setText("" + updatingEmployee.getSalary());

                        jBtnLoad.setVisible(false);
                        jTxtID.setVisible(false);

                    } catch (SQLException ex) {
                        Logger.getLogger(UpdateEmployee.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Employee not found.");
                }
            } catch (SQLException ex) {
                Logger.getLogger(UpdateEmployee.class.getName()).log(Level.SEVERE, null, ex);

            }
        }

    }//GEN-LAST:event_jBtnLoadActionPerformed
//If cancel then remove all text and hide update and cancel buttons, load visible.
    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
        
        jTxtName.setText("");
        jTxtAge.setText("");
        jTxtDepartment.setText("");
        jTxtSalary.setText("");
        jTxtID.setText("");
        
        setUpdateInvisible();
    }//GEN-LAST:event_jBtnCancelActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        
        //Get all info from inputs and validate it
        boolean valid = true;

        String name = jTxtName.getText();
        String department = jTxtDepartment.getText();
        
        int id = Integer.parseInt(jTxtID.getText());
        
        int age = 0;
        try {
            age= Integer.parseInt(jTxtAge.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid age, please put a valid input.");
            valid = false;
        }
        
        double salary = 0.00;
        try {
            salary= Double.parseDouble(jTxtSalary.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid salary, please put a valid input.");
            valid = false;
        }
        //If all valid, create new employee with all info
        if(!name.isEmpty()&&!department.isEmpty()&&salary>0&&age>0){
                
          
                Employee employee = new Employee(id,name,age,department,salary);
            //Use updateEmployee method to update the employee    
            try {
                
                db.updateEmployee(employee);
                JOptionPane.showMessageDialog(this, "Employee updated successfully.");  
                jTxtAge.setText("");
                jTxtDepartment.setText("");
                jTxtName.setText("");
                jTxtSalary.setText("");
                
                setUpdateInvisible();
                
            } catch (SQLException ex) {
                Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Error updating the employee.");
            }
     
        }else{
            JOptionPane.showMessageDialog(this, "Invalid input.");
        }
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateEmployee dialog = new UpdateEmployee(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
//Mehtods to set text and buttons visible /invisible more easily.
    public void setUpdateInvisible() {
        jBtnCancel.setVisible(false);
        jBtnUpdate.setVisible(false);
        jTxtName.setVisible(false);
        jTxtAge.setVisible(false);
        jTxtDepartment.setVisible(false);
        jTxtSalary.setVisible(false);
        
        jTxtID.setVisible(true);
        jBtnLoad.setVisible(true);
    }

    public void setUpdateVisible() {
        jBtnCancel.setVisible(true);
        jBtnUpdate.setVisible(true);
        jTxtName.setVisible(true);
        jTxtAge.setVisible(true);
        jTxtDepartment.setVisible(true);
        jTxtSalary.setVisible(true);
        
        jTxtID.setVisible(false);
        jBtnLoad.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnLoad;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane jTxtAge;
    private javax.swing.JTextPane jTxtDepartment;
    private javax.swing.JTextPane jTxtID;
    private javax.swing.JTextPane jTxtName;
    private javax.swing.JTextPane jTxtSalary;
    // End of variables declaration//GEN-END:variables
}
